CREATE FUNCTION sync_address_table()
 RETURNS trigger AS
$BODY$
BEGIN
  INSERT INTO address(ADDRESS_STREET,ADDRESS_CITY,ADDRESS_ZIP,ADDRESS_COUNTRY)
  VALUES (NEW.ADDRESS_STREET,NEW.ADDRESS_CITY,NEW.ADDRESS_ZIP,NEW.ADDRESS_COUNTRY);
  RETURN NEW;
END;
$BODY$
LANGUAGE plpgsql VOLATILE COST 100;

CREATE TRIGGER sync_address_table
  BEFORE INSERT
  ON person
  FOR ROW
  EXECUTE PROCEDURE sync_address_table();
